jacob:
    base_url: https://jacobsschool.ucsd.edu/faculty/profiles
    profile_base_url: https://jacobsschool.ucsd.edu
    data_dir: data/ucsd/engineering

economics:
    base_url: https://economics.ucsd.edu/faculty-and-research/faculty-profiles/index.html
    profile_base_url: https://economics.ucsd.edu/faculty-and-research/faculty-profiles
    data_dir: data/ucsd/economics

hdsi:
    base_url: https://datascience.ucsd.edu/faculty
    profile_base_url: https://datascience.ucsd.edu/people
    data_dir: data/ucsd/datascience